from typing import Protocol, AsyncIterator

class LLMService(Protocol):
    async def complete(self, messages: list[dict[str, str]]) -> str: ...
    async def stream(self, messages: list[dict[str, str]]) -> AsyncIterator[str]: ...
