from typing import Protocol
from datetime import timedelta

class TokenService(Protocol):
    def create_access_token(self, sub: str, expires_delta: timedelta | None = None) -> str: ...
    def create_refresh_token(self, sub: str, expires_delta: timedelta | None = None) -> str: ...
    def decode(self, token: str) -> dict: ...
